# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fft_0/fft_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_0 || ORIG_REF_NAME==fft_0} -quiet] -quiet
