webtalk_init -webtalk_dir /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.sim/sim_1/behav/xsim/xsim.dir/xdft_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 10 17:41:13 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211398127_174154042_210717994_026" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "301cfb997bfc565a808f39d1f16b82b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "16aeed7aa3784d85a0906363a0177721" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1593.093 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "185375 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "10.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "142496_KB" -context "xsim\\usage"
webtalk_transmit -clientid 483536648 -regid "211398127_174154042_210717994_026" -xml /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.sim/sim_1/behav/xsim/xsim.dir/xdft_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.sim/sim_1/behav/xsim/xsim.dir/xdft_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.sim/sim_1/behav/xsim/xsim.dir/xdft_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
