# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/soc/Volume/master-thesis/ft_cores/intfftk/intfftk.srcs/sources_1/ip/float_to_fixed18_0/float_to_fixed18_0.xci
# IP: The module: 'float_to_fixed18_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/soc/Volume/master-thesis/ft_cores/intfftk/intfftk.srcs/sources_1/ip/float_to_fixed18_0/float_to_fixed18_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_fixed18_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/soc/Volume/master-thesis/ft_cores/intfftk/intfftk.srcs/sources_1/ip/float_to_fixed18_0/float_to_fixed18_0.xci
# IP: The module: 'float_to_fixed18_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/soc/Volume/master-thesis/ft_cores/intfftk/intfftk.srcs/sources_1/ip/float_to_fixed18_0/float_to_fixed18_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_fixed18_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
