# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dft_fixed18_to_float_0/dft_fixed18_to_float_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dft_fixed18_to_float_0 || ORIG_REF_NAME==dft_fixed18_to_float_0} -quiet] -quiet
