# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.cache/wt [current_project]
set_property parent.project_path /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_output_repo /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/imports/new/fourier_transform_v1_0_user_logic.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/int_addsub_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/buffers/int_bitrev_order.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/cmult/int_cmult18x25_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt42x18_dsp48e1.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt44x18_dsp48e2.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/cmult/int_cmult_dbl18_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt35x25_dsp48e1.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt35x27_dsp48e2.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/cmult/int_cmult_dbl35_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt59x18_dsp48e1.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt61x18_dsp48e2.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/cmult/int_cmult_trpl18_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt52x25_dsp48e1.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/mults/mlt52x27_dsp48e2.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/cmult/int_cmult_trpl52_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/math/cmult/int_cmult_dsp48.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_fly_fd.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_fly_fd2.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/buffers/ramb_dp_one_clk.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_fly_spd.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_fly_addsub.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_fly_twd.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/twiddle/row_twiddle_tay.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/twiddle/rom_twiddle_int.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_spdf_dif2.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/butterflies/int_spdf_fftNk.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/src/main/int_spdf_fft_only.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/imports/intfftk/math_pkg.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/new/intfft_spdf_wrapper.vhd
  /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/imports/imports/new/fourier_transform_v1_0.vhd
}
read_ip -quiet /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fifo_out_0/intfft_spdf_fifo_out_0.xci
set_property used_in_implementation false [get_files -all /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fifo_out_0/intfft_spdf_fifo_out_0.xdc]
set_property used_in_implementation false [get_files -all /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fifo_out_0/intfft_spdf_fifo_out_0_ooc.xdc]

read_ip -quiet /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fifo_in_0/intfft_spdf_fifo_in_0.xci
set_property used_in_implementation false [get_files -all /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fifo_in_0/intfft_spdf_fifo_in_0.xdc]
set_property used_in_implementation false [get_files -all /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fifo_in_0/intfft_spdf_fifo_in_0_ooc.xdc]

read_ip -quiet /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fixed25_to_float_0/intfft_spdf_fixed25_to_float_0.xci
set_property used_in_implementation false [get_files -all /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_fixed25_to_float_0/intfft_spdf_fixed25_to_float_0_ooc.xdc]

read_ip -quiet /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_float_to_fixed18_0/intfft_spdf_float_to_fixed18_0.xci
set_property used_in_implementation false [get_files -all /media/soc/Volume/master-thesis/ft_cores/intfft_spdf/intfft_spdf.srcs/sources_1/ip/intfft_spdf_float_to_fixed18_0/intfft_spdf_float_to_fixed18_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top fourier_transform_v1_0 -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fourier_transform_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fourier_transform_v1_0_utilization_synth.rpt -pb fourier_transform_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
