# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.srcs/sources_1/ip/dft_fifo_out_0/dft_fifo_out_0.xci
# IP: The module: 'dft_fifo_out_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.srcs/sources_1/ip/dft_fifo_out_0/dft_fifo_out_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_fifo_out_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.srcs/sources_1/ip/dft_fifo_out_0/dft_fifo_out_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_fifo_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.srcs/sources_1/ip/dft_fifo_out_0/dft_fifo_out_0.xci
# IP: The module: 'dft_fifo_out_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.srcs/sources_1/ip/dft_fifo_out_0/dft_fifo_out_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_fifo_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/soc/Volume/master-thesis/ft_cores/xdft/xdft.srcs/sources_1/ip/dft_fifo_out_0/dft_fifo_out_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_fifo_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
