# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dblclkfft_fixed25_to_float_0/dblclkfft_fixed25_to_float_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dblclkfft_fixed25_to_float_0 || ORIG_REF_NAME==dblclkfft_fixed25_to_float_0} -quiet] -quiet
